# Project Description

Find all numbers that appear at least three times consecutively.

- **Return the result table in any order.**

## Example

### Input:
**Logs table:**
| id | num |
|----|-----|
| 1  | 1   |
| 2  | 1   |
| 3  | 1   |
| 4  | 2   |
| 5  | 1   |
| 6  | 2   |
| 7  | 2   |

### Output:
| ConsecutiveNums |
|-----------------|
| 1               |

# Intuition
The intuition is to compare each number with the two numbers before it to check if they are the same, indicating at least three consecutive occurrences.

# Approach
We'll use window functions (`LAG`) to access previous rows' values. By comparing the current number with the numbers two and one rows back, we can identify when a number appears at least three times in a row.

# Complexity
- **Time complexity:**
  O(n log n) due to the sorting implied by `ORDER BY` in window functions. However, with indexing, this might effectively be closer to $$O(n)$$.

- **Space complexity:**
  O(n), as we're creating a subquery with additional columns for each row of the original table.

# Code
```sql
SELECT DISTINCT num AS ConsecutiveNums
FROM (
    SELECT *,
        LAG(num, 1) OVER (ORDER BY id) AS first_lag1,
        LAG(num, 2) OVER (ORDER BY id) AS first_lag2
    FROM
        Logs
) LAGS_1_2
WHERE
    num = first_lag1 AND first_lag1 = first_lag2

# Second less efficient solution
### Code (Triple Join Solution)
```sql
SELECT DISTINCT l1.num AS ConsecutiveNums
FROM Logs l1
JOIN Logs l2 ON l1.id = l2.id - 1
JOIN Logs l3 ON l1.id = l3.id - 2
WHERE l1.num = l2.num AND l2.num = l3.num;

```
This approach involves joining the `Logs` table to itself three times to check for consecutive numbers. Each join shifts the row index by one, allowing us to compare each number with the two numbers before it.

# Complexity
- **Time complexity:**
  O(n^3) in the worst case due to the triple join. This can be high for large datasets as it results in many comparisons.

- **Space complexity:**
  O(n) for the result set, but the operation might require more temporary space due to the joins.