# Project Description

Write a solution to find the employees who are high earners in each of the company's departments. A high earner in a department is an employee who has a salary in the top three unique salaries for that department.

## Example

### Input:

**Employee Table:**
| id | name  | salary | departmentId |
|----|-------|--------|--------------|
| 1  | Joe   | 85000  | 1            |
| 2  | Henry | 80000  | 2            |
| 3  | Sam   | 60000  | 2            |
| 4  | Max   | 90000  | 1            |
| 5  | Janet | 69000  | 1            |
| 6  | Randy | 85000  | 1            |
| 7  | Will  | 70000  | 1            |

**Department Table:**
| id | name  |
|----|-------|
| 1  | IT    |
| 2  | Sales |

### Output:
| Department | Employee | Salary |
|------------|----------|--------|
| IT         | Max      | 90000  |
| IT         | Joe      | 85000  |
| IT         | Randy    | 85000  |
| IT         | Will     | 70000  |
| Sales      | Henry    | 80000  |
| Sales      | Sam      | 60000  |

**Explanation:**
- In IT, Max earns the highest unique salary, Joe and Randy share the second-highest, and Will has the third-highest.
- In Sales, Henry earns the highest, Sam the second, and there's no third as only two employees exist.

# Intuition
We need to rank salaries within each department, ensuring that ties for top positions are included. Using a window function like `DENSE_RANK()` will allow us to assign ranks without gaps, which is necessary for this problem.

# Approach
We'll use a CTE to:
1. Join the `Employee` and `Department` tables.
2. Rank each employee's salary within their department.
3. Select only those employees whose rank is in the top three.

# Complexity
- **Time complexity**: $$O(n \log n)$$, where n is the number of employees, due to sorting for ranking.
- **Space complexity**: $$O(n)$$ for the intermediate results stored in the CTE.

# Code

```sql
WITH cte AS (
    SELECT 
        d.name AS Department,
        e.name AS Employee,
        e.salary AS Salary,
        DENSE_RANK() OVER (PARTITION BY d.name ORDER BY Salary DESC) AS rnk
    FROM Employee e
    JOIN Department d ON e.departmentId = d.id
)
SELECT Department, Employee, Salary
FROM cte
WHERE rnk <= 3
ORDER BY Department, Salary DESC;