# Project Description

Write a solution to swap the seat id of every two consecutive students. If the number of students is odd, the id of the last student is not swapped.

Return the result table ordered by id in ascending order.

## Example

### Input:
**Seat table:**
| id | student |
|----|---------|
| 1  | Abbot   |
| 2  | Doris   |
| 3  | Emerson |
| 4  | Green   |
| 5  | Jeames  |

### Output:
| id | student |
|----|---------|
| 1  | Doris   |
| 2  | Abbot   |
| 3  | Green   |
| 4  | Emerson |
| 5  | Jeames  |

# Intuition
The problem involves rearranging seat numbers for students where every two students swap their seats unless one student is left unpaired due to an odd count. Here's the thought process:

- **Pairing Logic**: Swap the `id` of even and odd students where possible.
- **Last Student**: If there's an odd number of students, the last student remains in their seat.

# Approach

1. **Use CASE Statement**: 
   - Check if the current `id` is even or odd to decide the pairing.
   - If `id` is even, swap with the previous odd `id`.
   - If `id` is odd, check if it's the maximum `id` (last student) to avoid swapping if unpaired.
2. **Ordering**: Ensure the result is sorted by the new `id` in ascending order.

# Complexity

- **Time Complexity**: O(N log N) due to the `ORDER BY` clause which sorts the result.
- **Space Complexity**: O(N) as SQL might need extra space for sorting, depending on the database system.

# Code

```sql
SELECT 
    CASE 
        WHEN id = (SELECT MAX(id) FROM Seat) AND id % 2 != 0 THEN id
        WHEN id % 2 = 0 THEN id - 1
        ELSE id + 1
    END AS id,
    student
FROM Seat
ORDER BY id ASC;