# Project Description

Write an SQL query that reports the average experience years of all the employees for each project, rounded to 2 digits.

- **Return the result table in any order.**

## Example

### Input:
**Project table:**
| project_id | employee_id |
|------------|-------------|
| 1          | 1           |
| 1          | 2           |
| 1          | 3           |
| 2          | 1           |
| 2          | 4           |

**Employee table:**
| employee_id | name   | experience_years |
|-------------|--------|------------------|
| 1           | Khaled | 3                |
| 2           | Ali    | 2                |
| 3           | John   | 1                |
| 4           | Doe    | 2                |

### Output:
| project_id | average_years |
|------------|---------------|
| 1          | 2.00          |
| 2          | 2.50          |

## Intuition
The problem involves aggregating data from two tables, `Project` and `Employee`, to calculate an average experience for employees associated with each project. My first thought would be to:

- Join the `Project` table with the `Employee` table based on `employee_id` to connect projects with their employees.
- Use an aggregation function (`AVG`) to compute the average years of experience for employees in each project.
- Group the results by `project_id` since we want one row per project in the output.

## Approach
Here's how I would approach this:

- **Join Tables**: Use an `INNER JOIN` (or `JOIN`) because we only care about projects where there are matching employees. This ensures we only look at valid project-employee combinations.
- **Calculate Average**: After joining, apply `AVG` on the `experience_years` column from the `Employee` table to get the average experience for each project.
- **Group by Project**: Use `GROUP BY` with `project_id` from the `Project` table to ensure the average is calculated per distinct project.
- **Select and Alias**: Select the `project_id` and the calculated average, aliasing the average as `average_years`.

## Complexity

- **Time complexity:**  
  The complexity here is largely determined by the join operation. Assuming both tables are indexed on `employee_id`, the join could be performed in approximately linear time with respect to the number of rows in the smaller table. However, for SQL operations like this, we usually consider:
  O(n log n) where n is the number of rows in the larger table. This is because, in the worst case, sorting might be involved for the grouping operation.

- **Space complexity:**  
  Space complexity would primarily be determined by the result set and any temporary data structures used by the SQL engine for joining, aggregating, and sorting. If we assume that the result set size is proportional to the number of unique projects (which is likely small compared to the total number of rows in both tables combined), then:
  O(m) where m is the number of unique `project_id`s. This is because we're grouping by `project_id`, so we only store one row per project in memory.


# Code
```sql
# Write code

SELECT p.project_id AS project_id,
    ROUND(AVG(e.experience_years),2) AS average_years
FROM
    Project p
JOIN
    Employee e ON  e.employee_id = p.employee_id
GROUP BY
    p.project_id
```