# SQL Query for Identifying Low Fat and Recyclable Products

## Problem Setup

We have a table called `Products` with the following schema:

- **product_id**: An integer representing the unique identifier for each product.
- **low_fats**: An enum field that can be 'Y' for low fat or 'N' for not low fat.
- **recyclable**: An enum field that can be 'Y' for recyclable or 'N' for not recyclable.

**Problem Statement**: We need to write an SQL query to find the `product_id` of products that are both low fat and recyclable. The result should list these IDs in any order.

## Example Tables

Here's an example of how the `Products` table might look:

```sql
+-------------+----------+------------+
| product_id  | low_fats | recyclable |
+-------------+----------+------------+
| 0           | Y        | N          |
| 1           | Y        | Y          |
| 2           | N        | Y          |
| 3           | Y        | Y          |
| 4           | N        | N          |
+-------------+----------+------------+

Intuition
The task requires us to filter products based on two conditions simultaneously:
They must be low fat (low_fats = 'Y').
They must be recyclable (recyclable = 'Y').

Approach
We will use a simple SQL SELECT statement with a WHERE clause to filter the products according to our criteria. No joins or subqueries are needed since all information is within a single table.

Steps:
Select: Choose only the product_id field from the Products table.
Filter: Apply conditions where low_fats and recyclable are both 'Y'.

Complexity
Time Complexity: O(n), where n is the number of rows in the Products table. Each row is evaluated once.
Space Complexity: O(1), as we are not using additional data structures that grow with input size. The space for storing the result is minimal.

SQL Query
Here's the SQL query to solve this problem:

SELECT 
    product_id
FROM 
    Products
WHERE 
    low_fats = 'Y' 
    AND recyclable = 'Y';